apiVersion: v1
class: Repository
kind: Resource
metadata:
    name: examples
    description: Examples of using Ops Catalog in Serving, Discovery, Fulfillment
    labels: {}
    annotations:
        discovery.ops.catalog/visibility: public
    tier: ""
    contact: ""
contact:
    owner: null
dependencies:
    upstream: []
    downstream: []
    providedBy: git.org-github
classification:
    tag: []
    domain: platform
    team: devexp
    capability: operations
properties: {}
includes:
    - internal
