apiVersion: v1
class: MessagingServer
kind: Store
metadata:
    name: kafka.kafka-1
    description: Kafka cluster kafka-1 available at kafka.ops-catalog.io:9092
    labels: {}
    annotations: {}
    tier: ""
    contact: ""
contact:
    owner: null
dependencies:
    upstream: []
    downstream: []
classification:
    tag: []
    domain: storage
    team: keepers
    capability: operations
properties: {}
includes:
    - internal
runtime:
    endpoint:
        - intent: address
          location: kafka.ops-catalog.io:9092
