apiVersion: v1
class: App
kind: Component
metadata:
    name: airflow
    description: deployment type found in k8s.k8s
    labels: {}
    annotations:
        discovery.ops.catalog/deploymentType: deployment
        discovery.ops.catalog/image: skhatri/airflow:2.0.2
        discovery.ops.catalog/namespace: default
        discovery.ops.catalog/replicas: "1"
    tier: ""
    contact: ""
contact:
    owner: null
dependencies:
    upstream: []
    downstream: []
classification:
    tag: []
    domain: platform
    team: devops
    capability: operations
properties: {}
includes:
    - internal
