apiVersion: v1
class: Ingress
kind: Endpoint
metadata:
    name: httpserver-ingress
    description: Ingress in Kubernetes Cluster http://localhost:8070
    labels:
        core.ops-catalog.io/name: httpserver
    annotations: {}
    tier: ""
    contact: ""
contact:
    owner: null
dependencies:
    upstream: []
    downstream: []
classification:
    tag: []
    domain: platform
    team: devops
    capability: operations
properties: {}
includes:
    - internal
    - platform
runtime:
    endpoint:
        - intent: entrypoint
          location: docs.ops-catalog.io,docs.ops-catalog.io
links:
    - type: definition
      url: http://localhost:8070/api/ingresses?namespace=any&labels=true&annotations=true
