apiVersion: v1
class: Repository
kind: Resource
metadata:
    name: airflow-by-example
    description: Bunch of Airflow Configurations and DAGs for Kubernetes, Spark based data-pipelines. Scale inside Kubernetes using spark kubernetes master. Secure it with keycloak
    labels: {}
    annotations:
        discovery.ops.catalog/visibility: public
    tier: ""
    contact: ""
contact:
    owner: null
dependencies:
    upstream: []
    downstream: []
    providedBy: git.personal-github
classification:
    tag: []
    domain: platform
    team: devexp
    capability: operations
properties: {}
includes:
    - internal
